### ISSUE TITLE
Master Issue (Road Map) Planned Release for 28th October

### ISSUE THREAD

**Issue by iamVP7** [web-ext-101/web-ext-101.github.io#1]
This issue is meta issue and can be considered as **Road Map** for this project.

- [ ] Create What is this project about
- [ ] What are webextension
- [ ] What is manifest.json
- [ ]  How to run a WebExtension

**API**
- [ ]  Chrome override URL

*Tabs API*
- [ ]  tabs.create() & onCreated Example
- [ ]  tabs.query() Current active tab Example 
- [ ]  tabs.remove() & onRemoved Example 
- [ ]  tabs.update() & onUpdated Example
- [ ]  tabs.move() & onMoved Example
- [ ]  tabs.duplicate() Example
- [ ]  tabs.reload() Example
- [ ]  tabs.query() based on patterns Example 
- [ ]  tabs.get() Example
- [ ]  tabs.executeScript() Example
- [ ]  tabs.insertCSS()  Example
- [ ]  tabs.removeCSS() Example
- [ ]  tabs.setZoom() Example

- [ ]  tabs. Example
